# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      sqfentity_gen|property_sqfentity:
        generate_for:
          - example/lib/model/*.dart
          - example/lib/model/test/*.dart
          - example_ns/lib/model/test/*.dart
      #sqfentity_gen|property_sqfentity_forms:
      #  generate_for:
      #    - lib/model/*.dart