name: sqfentity_gen
homepage: https://github.com/hhtokpinar/sqfEntity
description: SqfnEntity Model Generator. SQLite ORM for Flutter lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework. 

version: 2.1.2+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.1.0
  source_gen: ^1.1.0
  meta: ^1.7.0
  analyzer: ^2.3.0 #removed because code generator throws exception on iOs
