name: single_page_scrollable_website
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  common:
    path: ../common
  url_strategy: ^0.2.0
  scrollable_positioned_list: ^0.2.2
  tuple: ^2.0.0
  flutter_lorem: ^2.0.0
  equatable: ^2.0.3
