name: navigator_2
description: Flutter Navigator 2.0 for Authentication and Bootstrapping

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  common:
    path: ../common
  provider: ^6.0.1
  url_strategy: ^0.2.0
  tuple: ^2.0.0
  equatable: ^2.0.3

flutter:
  uses-material-design: true